[package]
name = "grist"
version = "0.1.0"
authors = ["rphelps"]
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.7"
default-features = false
features = [
    "dwmapi",
    "winbase",
    "windef",
    "winuser",
]

[dependencies]
bitarray = "0.1.2"
lazy_static = "1.3.0"
num = "0.2.0"
num-derive = "0.2"
num-traits = "0.2"
typenum = "1.10.0"
